# config.yaml
milvus:
  host: "192.168.1.102"
  port: 19530                # ���Ͷ˿�
  collection_name: "company_news_final"
  embedding_dim: 1536        # ����ά��
  search_params:
    metric_type: "COSINE"    # ��������������һ��
    nprobe: 128              # ��������
    limit: 10                # ���ؽ����

mysql:
  host: "192.168.1.101"
  port: 13306                # ���Ͷ˿�
  user: "news_user"
  password: "km101"          # ������������ʹ�û�������
  database: "stock_news"     # ���ݿ�����

market_data:
  host: "127.0.0.1"
  port: 3306
  user: "news_user"
  password: "km101"
  database: "market_data"

qwen:
  api_key: "sk-48d14c2089104df1"  # ������Ϣ�������
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  embedding_model: "text-embedding-v1"
  chat_model: "qwen-plus"

generation:
  temperature: 0.3          # �����¶�ϵ��
  top_p: 0.9                # ���Ĳ�������

data:
  test_path: "../data/test.txt"  # ��������·��
  batch_size: 500            # ����������С